database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: core_metamodel
  connectionTimeoutMillis: 3000
  app_db_client: knex
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback
application:
  # Local defaults
  payment_host: 'http://localhost:8086'
  local_host: 'http://localhost:8082'
  email_address: ${EMAIL_ADDRESS}
  email_password: ${EMAIL_PASSWORD}
  email_host: ${EMAIL_HOST}
  email_port: 993
  # cloud example
  # payment_host: 'https://<username>-payment-backend.cloud.dbos.dev'
  # local_host: 'https://<username>-shop-backend.cloud.dbos.dev'